
lane :ipa21 do
  s3(
    bucket: 'fastlane-plugin-s3-ios',
    region: 'us-west-1',
    ipa: './ipa21/BanditTheCat.ipa'
  )
end

lane :ipa24 do
  s3(
    bucket: 'fastlane-plugin-s3-ios',
    region: 'us-west-1',
    ipa: './ipa24/BanditTheCat.ipa'
  )
end

lane :apk1 do
  s3(
    bucket: 'fastlane-plugin-s3-android',
    region: 'us-west-1',
    apk: './apk1/BanditTheCat.apk',
  )
end

lane :apk2 do
  s3(
    bucket: 'fastlane-plugin-s3-android',
    region: 'us-west-1',
    apk: './apk2/BanditTheCat.apk'
  )
end
