
lane :ipa21_multi do
  aws_s3(
    bucket: 'fastlane-plugin-s3',
    region: 'us-east-2',
    app_directory: 'ios',
    ipa: './fastlane/ipa21/BanditTheCat.ipa'
  )
end

lane :apk1_multi do
  aws_s3(
    bucket: 'fastlane-plugin-s3',
    region: 'us-east-2',
    app_directory: 'android',
    apk: './fastlane/apk1/BanditTheCat.apk',
  )
end

lane :ipa21 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-ios',
    region: 'us-west-1',
    ipa: './fastlane/ipa21/BanditTheCat.ipa'
  )
end

lane :ipa24 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-ios',
    region: 'us-west-1',
    ipa: './fastlane/ipa24/BanditTheCat.ipa'
  )
end

lane :apk1 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-android',
    region: 'us-west-1',
    apk: './fastlane/apk1/BanditTheCat.apk',
  )
end

lane :apk2 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-android',
    region: 'us-west-1',
    apk: './fastlane/apk2/BanditTheCat.apk'
  )
end

lane :east do
  aws_s3(
    bucket: 'fastlane-plugin-s3-east',
    region: 'us-east-1',
    ipa: './fastlane/ipa21/BanditTheCat.ipa'
  )
end

after_all do
  puts Action.lane_context[SharedValues::S3_PLIST_OUTPUT_PATH]
  puts Actions.lane_context[SharedValues::S3_HTML_OUTPUT_PATH]
end
