
lane :ipa21_multi do
  aws_s3(
    bucket: 'fastlane-plugin-s3',
    region: 'us-east-2',
    app_directory: 'ios',
    ipa: './fastlane/ipa21/BanditTheCat.ipa'
  )
end

lane :apk1_multi do
  aws_s3(
    bucket: 'fastlane-plugin-s3',
    region: 'us-east-2',
    app_directory: 'android',
    apk: './fastlane/apk1/BanditTheCat.apk',
  )
end

lane :ipa21 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-ios',
    region: 'us-west-1',
    ipa: './fastlane/ipa21/BanditTheCat.ipa',
    source: './fastlane/ipa21/source',
    skip_html_upload: false,
    release_notes: 'Hey some notes <br/>And some other notes<br/>And some other'
  )
end

lane :ipa24 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-ios',
    region: 'us-west-1',
    ipa: './fastlane/ipa24/BanditTheCat.ipa',
    html_in_folder: true
  )
end

lane :apk1 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-android',
    region: 'us-west-1',
    apk: './fastlane/apk1/BanditTheCat.apk',
    source: './fastlane/apk1/source',
    skip_html_upload: false,
    release_notes: 'Hey some notes <br/>And some other notes<br/>And some other'
  )
end

lane :apk2 do
  aws_s3(
    bucket: 'fastlane-plugin-s3-android',
    region: 'us-west-1',
    apk: './fastlane/apk2/BanditTheCat.apk',
    html_in_folder: true
  )
end

lane :east do
  aws_s3(
    bucket: 'fastlane-plugin-s3-east',
    region: 'us-east-1',
    ipa: './fastlane/ipa21/BanditTheCat.ipa'
  )
end

lane :files_no_path do
  aws_s3(
    bucket: 'fastlane-plugin-s3-east',
    region: 'us-east-1',
    files: [
      './fastlane/testfile1.txt',
      './fastlane/testfile2.txt',
    ],
    folder: './fastlane/testdir1'
  )
end

lane :files do
  aws_s3(
    bucket: 'fastlane-plugin-s3-east',
    region: 'us-east-1',
    path: 'dafiles',
    files: [
      './fastlane/testfile1.txt',
      './fastlane/testfile2.txt',
    ],
    folder: './fastlane/testdir1'
  )
end

after_all do
  puts Action.lane_context[SharedValues::S3_PLIST_OUTPUT_PATH]
  puts Actions.lane_context[SharedValues::S3_HTML_OUTPUT_PATH]
end
